### ISSUE TITLE
The server specs the tests are ran on?

### ISSUE THREAD

**Issue by v3ss0n** [squeaky-pl/aiobenchmarks#6]
We are going to test it out too!

**Comment by squeaky-pl** [comment]
Indeed the link to: https://morepypy.blogspot.com.br/2017/03/async-http-benchmarks-on-pypy3.html is missing.

> 
The benchmark was performed on a public cloud scaleway x86_64 server launched in a Paris data center. The server was running Ubuntu 16.04.01 LTS and reported Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz CPU. CPython 3.5.2 (shipped by default in Ubuntu) was benchmarked against a pypy-c-jit-90326-88ef793308eb-linux64 snapshot of the 3.5 compatibility branch of PyPy.

**Comment by v3ss0n** [comment]
Ah , thanks i miss that.
